version: '3.8'

services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: ecobazaar-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: ecobazaar_db
      MYSQL_USER: ecobazaar_user
      MYSQL_PASSWORD: ecobazaar_password
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - ecobazaar-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # Spring Boot Application
  backend:
    build: .
    container_name: ecobazaar-backend
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SERVER_PORT=8080
      - DATABASE_URL=jdbc:mysql://mysql:3306/ecobazaar_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      - DB_USERNAME=ecobazaar_user
      - DB_PASSWORD=ecobazaar_password
      - JWT_SECRET=ecobazaarX2024SecretKeyForJWTTokenGeneration
      - CORS_ORIGINS=http://localhost:3000,http://localhost:5173
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - ecobazaar-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  mysql_data:

networks:
  ecobazaar-network:
    driver: bridge
